### ISSUE TITLE
Official Python 3.6 support

### ISSUE THREAD

**Issue by impredicative** [bd808/python-ib3#2]
Thanks for this wonderful package. Can Python 3.6 support be officially noted at https://pypi.python.org/pypi/ib3/ ? I assume this gets defined in `setup.py`.

**Comment by bd808** [comment]
The Python 3.6 trove classifier would need to be added to setup.py and a new release made. It seems likely that the library will work with 3.6 and even 3.7, but I haven't tested that myself.
