### ISSUE TITLE
ib3 ci is broken

### ISSUE THREAD

**Issue by ssbarnea** [bd808/python-ib3#4]
While the project has a .travis.yml file that is not functional being broken in multiple places, mainly both supported platfroms being broken.

In addition to this I have the impression that there are no unitttests at all which is very weird especially as there is a nose configuration but no test files are to be found, at all

This makes any attempt to contribute and improve ib3 a real stretch goal.

**Comment by bd808** [comment]
Travis CI integration issues have been fixed and a dummy test has been added so that it is at least clear where to add tests when someone figures out how/what to test.
